//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaitanet_Safiullin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balans
    {
        public int Id_Balans { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<decimal> Money { get; set; }
    
        public virtual User User { get; set; }
    }
}
