//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaitanet_Safiullin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderStatus = new HashSet<OrderStatus>();
        }
    
        public int Id_Order { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<int> Id_Product { get; set; }
        public string Comment { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderStatus> OrderStatus { get; set; }
    }
}
