//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaitanet_Safiullin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int Id_Status { get; set; }
        public Nullable<int> Id_Order { get; set; }
        public Nullable<int> Id_stat { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Stat Stat { get; set; }
    }
}
