//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaitanet_Safiullin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id_Product { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date_Redact { get; set; }
        public string Photo { get; set; }
        public string Info_Product { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
