//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaitanet_Safiullin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public Stat()
        {
            this.OrderStatus = new HashSet<OrderStatus>();
        }
    
        public int Id_stat { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<OrderStatus> OrderStatus { get; set; }
    }
}
