//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaitanet_Safiullin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Balans = new HashSet<Balans>();
            this.Order = new HashSet<Order>();
        }
    
        public int User_Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Id_Role { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> DateBirthday { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Balans> Balans { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual Role Role { get; set; }
    }
}
